//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransacciones
    {
        public long IdLog { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<short> IdTransaccion { get; set; }
    
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
