//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materias()
        {
            this.MateriaAlumnos = new HashSet<MateriaAlumnos>();
        }
    
        public int IdMateria { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdProfesor { get; set; }
        public Nullable<int> IdSalon { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MateriaAlumnos> MateriaAlumnos { get; set; }
        public virtual Profesores Profesores { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
