//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversidadesEntities : DbContext
    {
        public UniversidadesEntities()
            : base("name=UniversidadesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<LogTransacciones> LogTransacciones { get; set; }
        public virtual DbSet<MateriaAlumnos> MateriaAlumnos { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Profesores> Profesores { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccion { get; set; }
    }
}
